spring.application.name=clinicalsapi
spring.datasource.url=jdbc:postgresql://localhost:5432/clinicals
spring.datasource.username=postgres
spring.datasource.password=postgres

# Log level for the whole app
logging.level.root=WARN

# Log level for your specific package (DEBUG shows all logs)
logging.level.com.rupesh.copilot.clinicalsapi=DEBUG

# Log to a file (optional)
logging.file.name=logs/clinicalsapi.log

# Log pattern for console
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Log pattern for file
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n